### ISSUE TITLE
Home button disabled while receiving a call.

### ISSUE THREAD

**Issue by nihal697** [AICP/packages_apps_AicpExtras#35]
Hi,
when receiving a call the home navigation button stops working unless the call is ended or picked up. Back and Recents key work normally but home key should also work imo. Makes it easier to use the phone while ignoring the call.
Kindly make it default behaviour or an option to enable the key, whichever you deem fit.
Thanks.

**Comment by eyosen** [comment]
Device? I am assuming it's a hw keys device and you should be seeing an option in the hw_button settings for "Action on incomign call". You can set home button behavior there

**Comment by nihal697** [comment]
Sorry I didnt mention device as I thought it isnt device specific. It is Redmi note 7 Indian variant. Sadly no it has software keys.

**Comment by eyosen** [comment]
That doesnt make sense. That option is only available on hw key devices and the default value of the option is the previous behavior so nothing should be affected on your end.

**Comment by nihal697** [comment]
yeah. I only know that when i receive calls tapping on home key doesnt work. Let me know how may I help in resolving the issue. 😅

**Comment by eyosen** [comment]
Finished testing your report but unable to reproduce it. When a call is received, dialer is displayed on entire screen so navbar is not shown. When I place a call, navbar is shown and home button works as expected. Better get in touch with your device maintainer.
